// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClickSpace.DataAccess.Database
{
    public partial class CartProduct
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public long UserId { get; set; }

        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}