// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClickSpace.DataAccess.Database
{
    public partial class User
    {
        public User()
        {
            CartProduct = new HashSet<CartProduct>();
        }

        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime? RegisterDate { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public bool? IsAdmin { get; set; }
        public string ProfilePictureUrl { get; set; }
        public string PhoneNumber { get; set; }

        public virtual ICollection<CartProduct> CartProduct { get; set; }
    }
}